//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndComplete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipient()
        {
            this.Donations = new HashSet<Donation>();
        }
    
        public int RecipientID { get; set; }
        public System.DateTime DateOfUse { get; set; }
        public string RelatedCondition { get; set; }
        public string RecipientCodedName { get; set; }
        public Nullable<int> DonationID { get; set; }
        public Nullable<bool> RecipientIsDeleted { get; set; }
        public Nullable<int> DonorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donations { get; set; }
        public virtual Donation Donation { get; set; }
        public virtual Donor Donor { get; set; }
    }
}
